include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - dart_code_metrics

linter:
  rules:
    always_put_required_named_parameters_first: false
    comment_references: false
    directives_ordering: false
    sort_pub_dependencies: false

dart_code_metrics:
  extends:
    - package:dart_code_metrics/presets/all.yaml
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
    source-lines-of-code: 134
    halstead-volume: 10926
  anti-patterns:
    - long-method:
        exclude:
          - test/**
  metrics-exclude:
    - test/**
  rules:
    - arguments-ordering: false
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-top-level-members-in-tests: false
    - format-comment: false
    - prefer-commenting-analyzer-ignores: false
    - prefer-moving-to-variable:
        allowed-duplicated-chains: 3
    - prefer-static-class: false